### ISSUE TITLE
炫一点的CSS属性们

### ISSUE THREAD

**Issue by findxc** [findxc/blog#4]
## [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)
用于实现一些简单的多边形。[这个网站](http://bennettfeely.com/clippy/)可以比较方便地生成CSS代码。

## [box-shadow](https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-shadow)
该属性支持设置内阴影，支持设置多个阴影效果。

## [drop-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
`filter`的这个值用于对不规则形状生成阴影。
![image](https://user-images.githubusercontent.com/24750971/39522250-60519460-4e44-11e8-9820-ea7f2a052145.png)

```html
<body>
  <div id='main'></div>
</body>
```
```css
#main {
  position: relative;
  width: 120px;
  height: 120px;
  filter: drop-shadow(10px 10px lightskyblue);
}

#main::after {
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  background: lightpink;
  clip-path: polygon(0 0, 100% 0, 100% 80%, 50% 100%, 0 80%);
}
```

## [background](https://developer.mozilla.org/zh-CN/docs/Web/CSS/background)
`background`可以是多个效果的合成，用逗号连起来就好了。像下图这边渐变其实就是两个背景给叠加出来的。
![image](https://user-images.githubusercontent.com/24750971/39522929-7be0067e-4e46-11e8-9dc1-4da05c7ed318.png)
```html
<body>
  <div id='main'></div>
</body>
```
```css
#main {
  width: 120px;
  height: 120px;
  background: 
    linear-gradient(to bottom,transparent 50%, lightskyblue 50%) center/100% 10%,
    linear-gradient(to bottom,lightpink 50%, transparent 50%) center/100% 10%;
}
```
