### ISSUE TITLE
记录一次从零开始给服务器装 ubuntu 18.04 系统

### ISSUE THREAD

**Issue by findxc** [findxc/blog#66]
从零开始分为以下几个步骤：

1. 下载系统的镜像
2. 制作安装系统用的U盘
3. 用U盘给服务器装系统
4. 为服务器配置网络

## 1. 下载系统的镜像
一开始我用的镜像是在[清华大学开源软件镜像站](https://mirrors.tuna.tsinghua.edu.cn/#)上下载的：
![image](https://user-images.githubusercontent.com/24750971/58365819-04dd9680-7efc-11e9-9511-625cdfbfe1ac.png)

结果这个镜像在安装过程中一定要配置网络，不能跳过，而装系统时不知道为什么配置网络一直不成功...尴尬，就只好重新下载了一个不需要配置网络的镜像，下载链接为 http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso 。

后面查了下，镜像名中含有`live`的表示安装系统过程中需要配置网络。
![image](https://user-images.githubusercontent.com/24750971/58367392-3a40af00-7f11-11e9-95a3-86ff826c54f2.png)

**划重点：以后再装系统尽量就用不需要配置网络的镜像，比较省心。**

## 2. 制作安装系统用的U盘

先在 https://rufus.ie/ 上下载制作安装盘用的软件。

![image](https://user-images.githubusercontent.com/24750971/58367425-ab806200-7f11-11e9-9599-e447b51e71d9.png)

在电脑上插入U盘，然后启动该软件，在界面上选择**设备**和**引导类型**后点击底部的**开始**就行了。

![image](https://user-images.githubusercontent.com/24750971/58367436-d66ab600-7f11-11e9-8da9-62559560f633.png)

## 3. 用U盘给服务器装系统

给服务器插上咱做好的U盘，在服务器开机过程中按住某个键（可能是F11或者别的键，可以根据服务器牌子查一下按什么键）进入BIOS界面，选择以U盘启动，然后一路选选选就装完系统了。

## 4. 为服务器配置网络

首先需要知道是给哪个网卡配置，如果只有一个网卡的话直接`ifconfig -a`去看就行了。如果服务器有多个网卡，可以用`ethtool -p 网卡名`去判断网口对应的网卡，执行命令后网口会闪烁。

https://netplan.io/examples 这里有网络配置的举例。我是需要给服务器配置静态ip，所以在`/etc/netplan/`下配置一个`.yaml`文件，内容为：

```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:  # 网卡名字
      dhcp4: no
      addresses:
        - 10.10.10.2/24  # 静态ip和掩码值
      gateway4: 10.10.10.1  # 网关值
      nameservers:
        addresses: [114.114.114.114]  # 域名解析服务器地址
```

然后执行`sudo netplan apply`使该配置生效即可。然后可以ping一下其它服务器测试下网络配置是否成功了。

以上就是装服务器的所有过程啦。
